# Generated by Django 3.1.2 on 2020-11-19 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('planName', models.CharField(max_length=30)),
                ('price', models.BigIntegerField()),
                ('registrationFee', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('discription', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100, null=True)),
                ('joiningDate', models.DateField(default=datetime.datetime.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.plan')),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('latFeePaid', models.DateField(default=datetime.datetime.now)),
                ('feeStatus', models.BooleanField(default=False)),
                ('paidAmount', models.BigIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentregistration')),
            ],
        ),
    ]
