# Generated by Django 3.1.2 on 2020-11-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='latFeePaid',
            new_name='lastFeePaid',
        ),
    ]
