# Generated by Django 3.1.2 on 2020-11-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201119_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='paid',
        ),
    ]
